spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    maximumPoolSize: 1
    hikari:
      connectionTimeout: 5000
      idleTimeout: 1000
      maxLifetime: 30000
      minimumIdle: 0
      maximumPoolSize: 1
  jpa:
    hibernate.ddl-auto: none