spring:
  datasource:
    url: jdbc:postgresql://ec2-52-202-66-191.compute-1.amazonaws.com:5432/d5789alpb91f6i
    username: ejavpeutvtrooo
    password: invalida
    maximumPoolSize: 1
    hikari:
      connectionTimeout: 5000
      idleTimeout: 1000
      maxLifetime: 30000
      minimumIdle: 0
      maximumPoolSize: 1
  jpa:
    hibernate.ddl-auto: none